on:
  push:
    tags:        
      - v1.*

jobs:
  build_and_push:
    name: Build and Push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: docker-compose build
      - name: Push image
        run: docker-compose push

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: install openssh
        run: apt install openssh-server
      - name: run ssh commands 
        run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} -i ${{ secrets.VPS_KEY }} -p ${{ secrets.VPS_PORT }} ; cd /cumin
              docker-compose stop
              docker-compose rm -f
              docker-compose pull
              docker-compose up -d
